// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLg_jqIXKcYXL_gDd53uKha6B-w-UYGwY',
    appId: '1:413693693293:web:3e12b1cfcd871510971e64',
    messagingSenderId: '413693693293',
    projectId: 'wordpuzzle-medat',
    authDomain: 'wordpuzzle-medat.firebaseapp.com',
    storageBucket: 'wordpuzzle-medat.appspot.com',
    measurementId: 'G-26BPVRJSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsvGmwwtUuuEhjQ6n2u1NTClo2hDXVd4',
    appId: '1:413693693293:android:1adb411e7acf0304971e64',
    messagingSenderId: '413693693293',
    projectId: 'wordpuzzle-medat',
    storageBucket: 'wordpuzzle-medat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rjcIGc6mVb43YirosiNU1WeYht0IBbA',
    appId: '1:413693693293:ios:7612d052d30f6255971e64',
    messagingSenderId: '413693693293',
    projectId: 'wordpuzzle-medat',
    storageBucket: 'wordpuzzle-medat.appspot.com',
    iosBundleId: 'com.maintobias.wordpuzzle.wordpuzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2rjcIGc6mVb43YirosiNU1WeYht0IBbA',
    appId: '1:413693693293:ios:6746e942cce2d529971e64',
    messagingSenderId: '413693693293',
    projectId: 'wordpuzzle-medat',
    storageBucket: 'wordpuzzle-medat.appspot.com',
    iosBundleId: 'com.maintobias.wordpuzzle.wordpuzzle.RunnerTests',
  );
}
